import {chromium} from 'playwright';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const base=process.env.BRAND_QA_URL||'http://127.0.0.1:4317/';
const dir='/tmp/silicon-brand-research/qa';fs.mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('.card').count(),20);await page.screenshot({path:dir+'/desktop.png',fullPage:true});
await page.locator('[data-save="05"]').click();await page.locator('[data-save="10"]').click();await page.locator('#compare').click();assert(await page.locator('#compare-dialog').evaluate(x=>x.open));assert.equal(await page.locator('.compare-grid article').count(),2);await page.screenshot({path:dir+'/compare.png'});await page.getByRole('button',{name:'Close comparison'}).click();
await page.locator('.canvas[data-open="05"]').click();assert(await page.locator('#detail').evaluate(x=>x.open));assert.equal(await page.locator('#detail-title').textContent(),'Impeller');await page.screenshot({path:dir+'/detail.png'});await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#detail-title').textContent(),'Wafer pair');await page.keyboard.press('Escape');assert(!(await page.locator('#detail').evaluate(x=>x.open)));
await page.locator('#preview-mode').selectOption('light');assert.equal(await page.locator('.canvas.light').count(),20);await page.screenshot({path:dir+'/light-on-slate.png'});await page.locator('#preview-mode').selectOption('color');
await page.locator('[data-filter="Compute"]').click();assert.equal(await page.locator('.card').count(),7);await page.locator('[data-filter="All"]').click();await page.locator('#show-saved').click();assert.equal(await page.locator('.card').count(),2);await page.locator('#show-saved').click();await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('.save.saved').count(),2);
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:width<500?844:1050});await page.evaluate(()=>window.scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);if(width===390)await page.screenshot({path:dir+'/mobile.png',fullPage:true});await page.locator('.canvas[data-open="19"]').click();assert(await page.locator('#detail').evaluate(x=>x.scrollWidth<=x.clientWidth+1),`Modal overflow at ${width}`);if(width===390)await page.screenshot({path:dir+'/mobile-detail.png'});await page.getByRole('button',{name:'Close preview'}).click();}
await page.goto(base+'#logo-16',{waitUntil:'networkidle'});assert.equal(await page.locator('#detail-title').textContent(),'Flux');await page.keyboard.press('Escape');
for(const extension of ['svg','png']){const url=extension==='svg'?'marks/silicon-05-master.svg':'marks/silicon-05-master-2048.png';const response=await page.request.get(new URL(url,base).href);assert.equal(response.status(),200);assert(response.headers()['content-type'].includes(extension==='svg'?'svg':'png'));}
assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/result.json',JSON.stringify({base,concepts:20,viewportWidths:[320,390,768,1440],checks:['favorites save and reload','compare two choices','modal keyboard navigation','light and dark exact recolour previews','category filter','saved-only filter','direct logo link','SVG and PNG downloads','no horizontal overflow','no JavaScript errors'],errors},null,2));console.log(JSON.stringify({base,concepts:20,checks:'passed',errors}));await browser.close();
