import './style.css';
import concepts from './concepts.json';
import references from './references.json';
type Concept=(typeof concepts)[number];
type Mode='color'|'ink'|'light';
const root=document.querySelector<HTMLDivElement>('#app')!;
const icons={heart:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 22l8.8-9.5a5.5 5.5 0 0 0 0-7.8Z"/></svg>',arrow:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',download:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/></svg>',close:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="m6 6 12 12M6 18 18 6"/></svg>'};
let mode:Mode='color',filter='All',onlySaved=false;
let active:Concept|undefined;
let saved=new Set<string>();
try{const value:unknown=JSON.parse(localStorage.getItem('silicon-logo-study-20260929')||'[]');if(Array.isArray(value))saved=new Set(value.filter((id):id is string=>typeof id==='string'&&concepts.some(c=>c.id===id)));}catch{/* A private browsing session can still use the shortlist. */}
const source=(c:Concept,m:Mode=mode)=>m==='color'?c.master:m==='ink'?c.ink:c.light;
const favorite=(c:Concept)=>`<button class="save ${saved.has(c.id)?'saved':''}" data-save="${c.id}" aria-label="${saved.has(c.id)?'Remove':'Save'} option ${c.id}" aria-pressed="${saved.has(c.id)}">${icons.heart}</button>`;
root.innerHTML=`
<header class="topbar"><a class="brand" href="#" aria-label="Silicon identity study home">silicon<span> / identity study</span></a><a class="text-link" href="silicon-20-logo-concepts.zip" download>Download all ${icons.download}</a></header>
<main><section class="intro"><div><div class="eyebrow">Symbol exploration · September 2026</div><h1>A mark for silicon.</h1><p>Twenty directions. Soft geometry, subtle hardware cues,<br class="desktop-break"> and enough character to stand on their own.</p></div><div class="intro-aside"><span class="edition">01 / 04</span><p>Start with the symbol.</p><span class="next-stages">Colour, avatar and banner follow.</span><a href="#standard" class="text-link">The references & direction ${icons.arrow}</a></div></section>
<section id="marks" aria-labelledby="marks-title"><div class="controls"><div class="filter-group" aria-label="Filter concepts"><h2 class="sr-only" id="marks-title">Logo concepts</h2>${['All','Silicon','Compute','Markets'].map(f=>`<button class="filter ${f==='All'?'active':''}" data-filter="${f}" aria-pressed="${f==='All'}">${f==='All'?'All 20':f}</button>`).join('')}</div><div class="preview-control"><label for="preview-mode">Preview</label><select id="preview-mode"><option value="color">Colour on white</option><option value="ink">Graphite on oat</option><option value="light">Light on slate</option></select></div></div><div class="gallery" id="gallery"></div><div class="empty" id="empty" hidden>No saved options in this view. Use the heart beside a mark to start a shortlist.</div><p class="comparison-note">The same scale on every card. Preview colours are exploratory. Every master has a transparent background.</p></section>
<section id="standard" class="standard"><div class="section-heading"><span class="eyebrow">The direction</span><h2>Quiet, precise, recognisable.</h2><p>A white-first identity with a soft technical character.<br>One strong silhouette should do most of the work.</p></div><div class="principles"><article><span>01</span><h3>A symbol with room to breathe.</h3><p>Clear counters, comfortable margins and enough weight to hold up in a tiny avatar.</p></article><article><span>02</span><h3>Hardware, softly expressed.</h3><p>Dies, fins, lattice cells and processing lanes distilled into simple geometry.</p></article><article><span>03</span><h3>Restrained colour with personality.</h3><p>Graphite and soft whites, with mineral blue, sage, clay and muted plum to explore.</p></article><article><span>04</span><h3>A system that can grow.</h3><p>Keep the symbol independent. Build colour studies, motion and a separate banner around the chosen mark.</p></article></div>
<details class="reference-details"><summary><span>What I took from the references</span><span>9 projects ${icons.arrow}</span></summary><div class="reference-grid">${references.map(r=>`<article><h3>${r.name}</h3><p>${r.take}</p><div class="reference-links"><a href="${r.site}" target="_blank" rel="noreferrer">Website ↗</a>${r.x?`<a href="${r.x}" target="_blank" rel="noreferrer">X profile ↗</a>`:'<span>X unverified</span>'}</div><small>${r.status}</small></article>`).join('')}</div><p class="research-note">Reviewed 29 September 2026. X images were retrieved from the public X image CDN using profile metadata from FxTwitter because direct X pages blocked access. Reference artwork is inspiration only and is not included in the logo downloads.</p></details></section>
<footer><span>Silicon · 20 original concepts</span><div><a href="assets.md">Asset record</a><a href="silicon-20-logo-concepts.zip" download>Download SVG + PNG</a></div><p>No logo or background has been approved. Save your favourites and share their numbers.</p></footer></main>
<aside class="shortlist" aria-label="Your shortlist"><button id="show-saved" aria-pressed="false">${icons.heart}<span id="saved-count">Shortlist · ${saved.size}</span></button><div id="saved-chips" class="saved-chips"></div><div class="shortlist-actions"><button id="copy-shortlist" class="quiet">Copy numbers</button><button id="compare" class="primary">Compare ${icons.arrow}</button></div></aside>
<dialog id="detail" aria-labelledby="detail-title"></dialog><dialog id="compare-dialog" aria-labelledby="compare-title"></dialog><div class="toast" role="status" aria-live="polite"></div>`;
const gallery=document.querySelector<HTMLDivElement>('#gallery')!;
const detail=document.querySelector<HTMLDialogElement>('#detail')!;
const comparison=document.querySelector<HTMLDialogElement>('#compare-dialog')!;
function card(c:Concept):string{return `<article class="card" id="card-${c.id}"><div class="card-top"><span class="number">${c.id}</span>${favorite(c)}</div><button class="canvas ${mode}" data-open="${c.id}" aria-label="View option ${c.id}, ${c.name}"><img class="hero-mark" src="${source(c)}" alt="${c.name} logo concept" width="240" height="240" loading="lazy"/><span class="view-label">Explore ${icons.arrow}</span></button><div class="card-caption"><div><h3><button data-open="${c.id}">${c.name}</button></h3><p>${c.family} · ${c.symmetry.toLowerCase()}</p></div><span class="avatar ${mode}" title="Circular avatar preview"><img src="${source(c)}" alt="" width="56" height="56" loading="lazy"/></span></div><div class="card-foot"><div class="size-samples"><span class="mini ${mode}" title="16 pixel preview"><img src="${source(c)}" alt="16 pixel ${c.name}" width="16" height="16"/>16</span><span class="mini ${mode}" title="32 pixel preview"><img src="${source(c)}" alt="32 pixel ${c.name}" width="32" height="32"/>32</span></div><div class="downloads"><a href="${c.master}" download="silicon-${c.id}-${c.name.toLowerCase().replaceAll(' ','-')}.svg" aria-label="Download option ${c.id} SVG">SVG</a><a href="${c.png}" download aria-label="Download option ${c.id} transparent PNG">PNG</a></div></div></article>`;}
function render(){const visible=concepts.filter(c=>(filter==='All'||c.family===filter)&&(!onlySaved||saved.has(c.id)));gallery.innerHTML=visible.map(card).join('');document.querySelector<HTMLElement>('#empty')!.hidden=visible.length!==0;renderShortlist();}
function renderShortlist(){document.querySelector('#saved-count')!.textContent=`Shortlist · ${saved.size}`;document.querySelector('#saved-chips')!.innerHTML=[...saved].sort().map(id=>`<button data-open="${id}" aria-label="Open saved option ${id}">${id}</button>`).join('');document.querySelector<HTMLButtonElement>('#compare')!.disabled=saved.size<2;document.querySelector<HTMLButtonElement>('#copy-shortlist')!.disabled=saved.size===0;document.querySelector<HTMLButtonElement>('#show-saved')!.setAttribute('aria-pressed',String(onlySaved));}
function save(id:string){if(saved.has(id))saved.delete(id);else saved.add(id);try{localStorage.setItem('silicon-logo-study-20260929',JSON.stringify([...saved]));}catch{}const focused=document.activeElement as HTMLElement|null;const wasDetail=detail.contains(focused);render();if(detail.open&&active){renderDetail(active);if(wasDetail)detail.querySelector<HTMLButtonElement>('[data-save]')?.focus();}else gallery.querySelector<HTMLButtonElement>(`[data-save="${id}"]`)?.focus();}
function renderDetail(c:Concept){detail.innerHTML=`<div class="dialog-header"><span class="eyebrow">Option ${c.id} / 20</span><div class="dialog-actions">${favorite(c)}<button data-close="detail" class="icon-button" aria-label="Close preview">${icons.close}</button></div></div><div class="detail-body"><div class="detail-visuals"><div class="detail-main checker"><img src="${c.master}" width="512" height="512" alt="Transparent master for ${c.name}"/><span>Transparent master</span></div><div class="theme-proofs"><div class="proof ink"><img src="${c.ink}" width="192" height="192" alt="Graphite version of ${c.name}"/><span>Graphite on oat</span></div><div class="proof light"><img src="${c.light}" width="192" height="192" alt="Light version of ${c.name}"/><span>Light on slate</span></div></div></div><div class="detail-copy"><p class="eyebrow">${c.family} · ${c.symmetry.toLowerCase()}</p><h2 id="detail-title">${c.name}</h2><p>${c.description}</p><div class="detail-avatars"><figure><div class="sample-square"><img src="${c.master}" width="96" height="96" alt="Square crop of ${c.name}"/></div><figcaption>Square</figcaption></figure><figure><div class="sample-circle"><img src="${c.master}" width="96" height="96" alt="Circular crop of ${c.name}"/></div><figcaption>Circle</figcaption></figure><figure class="actual-sizes"><div><img src="${c.master}" width="16" height="16" alt="16 pixel preview"/><img src="${c.master}" width="32" height="32" alt="32 pixel preview"/></div><figcaption>16 / 32 px</figcaption></figure></div><div class="palette-line"><span style="background:${c.color}" class="swatch"></span><span>${c.color} <span class="muted">· exploratory fill</span></span></div><div class="detail-downloads"><a class="primary" href="${c.master}" download>Transparent SVG ${icons.download}</a><a class="secondary" href="${c.png}" download>2048 px transparent PNG ${icons.download}</a><div><a href="${c.ink}" download>Graphite SVG</a><a href="${c.light}" download>Light SVG</a></div></div><p class="detail-note">One silhouette, exact recolours.<br>No wordmark or background baked into the files.</p></div></div><div class="dialog-footer"><button class="quiet" data-step="-1">← Previous</button><span>Use ← → to browse</span><button class="quiet" data-step="1">Next →</button></div>`;}
function openConcept(id:string){const c=concepts.find(c=>c.id===id);if(!c)return;active=c;renderDetail(c);if(!detail.open)detail.showModal();history.replaceState(null,'',`#logo-${id}`);}
function step(delta:number){if(!active)return;openConcept(concepts[(concepts.indexOf(active)+delta+concepts.length)%concepts.length].id);}
function openCompare(){const list=concepts.filter(c=>saved.has(c.id));if(list.length<2)return;comparison.innerHTML=`<div class="dialog-header"><div><p class="eyebrow">Your shortlist</p><h2 id="compare-title">Compare ${list.length} directions.</h2></div><button data-close="compare-dialog" class="icon-button" aria-label="Close comparison">${icons.close}</button></div><div class="compare-grid">${list.map(c=>`<article><button class="compare-mark ${mode}" data-open="${c.id}"><img src="${source(c)}" width="256" height="256" alt="Option ${c.id}, ${c.name}"/></button><h3>${c.id} · ${c.name}</h3><div class="compare-proofs"><span class="avatar ${mode}"><img src="${source(c)}" width="56" height="56" alt="Circular preview"/></span><img src="${c.master}" width="16" height="16" alt="16 pixel preview"/><img src="${c.master}" width="32" height="32" alt="32 pixel preview"/></div><p>${c.family} · ${c.symmetry.toLowerCase()}</p><a href="${c.master}" download>Download SVG ↗</a></article>`).join('')}</div><div class="dialog-footer"><span>Same scale. No selection is treated as approval.</span><button class="quiet" id="copy-comparison">Copy numbers</button></div>`;comparison.showModal();}
let toastTimer:ReturnType<typeof setTimeout>|undefined;
function toast(text:string){const el=document.querySelector<HTMLDivElement>('.toast')!;el.textContent=text;el.classList.add('visible');if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3000);}
async function copy(){const text=`Silicon logo shortlist: ${[...saved].sort().join(', ')}`;try{await navigator.clipboard.writeText(text);toast('Shortlist copied.');}catch{toast(text);}}
root.addEventListener('click',event=>{const el=(event.target as Element).closest<HTMLElement>('button,a');if(!el)return;if(el.dataset.save){save(el.dataset.save);return;}if(el.dataset.open){if(comparison.open)comparison.close();openConcept(el.dataset.open);return;}if(el.dataset.close){(document.getElementById(el.dataset.close) as HTMLDialogElement).close();return;}if(el.dataset.step){step(Number(el.dataset.step));return;}if(el.dataset.filter){filter=el.dataset.filter;document.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===filter);b.setAttribute('aria-pressed',String(b.dataset.filter===filter));});render();return;}if(el.id==='show-saved'){onlySaved=!onlySaved;render();document.querySelector('#marks')!.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}if(el.id==='compare')openCompare();if(el.id==='copy-shortlist'||el.id==='copy-comparison')void copy();});
document.querySelector<HTMLSelectElement>('#preview-mode')!.addEventListener('change',event=>{mode=(event.target as HTMLSelectElement).value as Mode;render();});
detail.addEventListener('close',()=>{history.replaceState(null,'','#marks');active=undefined;});
for(const dialog of [detail,comparison])dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close();});
document.addEventListener('keydown',e=>{if(!detail.open)return;if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}if(e.key==='ArrowRight'){e.preventDefault();step(1);}});
window.addEventListener('hashchange',()=>{const match=location.hash.match(/^#logo-(\d{2})$/);if(match)openConcept(match[1]);});
render();const initial=location.hash.match(/^#logo-(\d{2})$/);if(initial)openConcept(initial[1]);
