/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Config */
        get: operations["public_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_v1_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_history__market__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Methodology */
        get: operations["methodology_api_v1_methodology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receipts */
        get: operations["receipts_api_v1_receipts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{digest}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receipt */
        get: operations["receipt_api_v1_receipts__digest__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Access */
        get: operations["access_api_v1_access__address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote */
        post: operations["quote_api_v1_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Protocol */
        get: operations["protocol_api_v1_protocol_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_api_v1_portfolio__address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leaderboard */
        get: operations["leaderboard_api_v1_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_v1_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Access */
        Access: {
            /** Address */
            address: string;
            /** Usdg */
            usdg?: string | null;
            /** Eth */
            eth?: string | null;
            /** Token Balance */
            token_balance?: string | null;
            /**
             * Holder
             * @default false
             */
            holder: boolean;
            /**
             * Fee Free
             * @default false
             */
            fee_free: boolean;
            /**
             * Fee Bps
             * @default 100
             */
            fee_bps: number;
            /**
             * Advanced
             * @default false
             */
            advanced: boolean;
            /**
             * Token Configured
             * @default false
             */
            token_configured: boolean;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** Checked At */
            checked_at: string;
            /** Error */
            error?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderRow */
        LeaderRow: {
            /** Wallet */
            wallet: string;
            /** Trades */
            trades: number;
            /** Wins */
            wins: number;
            /** Pnl */
            pnl: string;
        };
        /** Leaderboard */
        Leaderboard: {
            /** Period */
            period: string;
            /** Rows */
            rows?: components["schemas"]["LeaderRow"][];
            /** Status */
            status: string;
        };
        /** Market */
        Market: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Architecture */
            architecture: string;
            /** Memory */
            memory: string;
            /** Color */
            color: string;
            /** Price */
            price?: number | null;
            /** Index */
            index?: number | null;
            /** Baseline */
            baseline?: number | null;
            /** Source Updated At */
            source_updated_at?: string | null;
            /** Collected At */
            collected_at?: string | null;
            /** History Since */
            history_since?: string | null;
            /**
             * Stale
             * @default true
             */
            stale: boolean;
            /**
             * Coverage
             * @default 0
             */
            coverage: number;
            /**
             * Quote Count
             * @default 0
             */
            quote_count: number;
            /**
             * Required Providers
             * @default 0
             */
            required_providers: number;
            /**
             * Status
             * @default collecting
             * @enum {string}
             */
            status: "collecting" | "tracking" | "benchmark" | "withheld";
            /** Changes */
            changes?: {
                [key: string]: number | null;
            };
            /** History */
            history?: components["schemas"]["Point"][];
            /** Providers */
            providers?: components["schemas"]["ProviderQuote"][];
        };
        /** Network */
        Network: {
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /** Block */
            block?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Checked At */
            checked_at?: string | null;
            /**
             * Chain Id
             * @default 4663
             */
            chain_id: number;
            /** Error */
            error?: string | null;
        };
        /** Point */
        Point: {
            /** Time */
            time: string;
            /** Price */
            price: number;
            /** Index */
            index: number;
        };
        /** Portfolio */
        Portfolio: {
            /** Positions */
            positions?: components["schemas"]["PositionView"][];
            /**
             * Writer Shares
             * @default 0
             */
            writer_shares: string;
            /**
             * Withdrawable
             * @default 0
             */
            withdrawable: string;
            /**
             * Index Synced
             * @default false
             */
            index_synced: boolean;
        };
        /** PositionView */
        PositionView: {
            /** Id */
            id: number;
            /** Buyer */
            buyer: string;
            /** Side */
            side: string;
            /** Units */
            units: string;
            /** Cost */
            cost: string;
            /** Cap */
            cap: string;
            /** Claimed */
            claimed: boolean;
            /** Claimable */
            claimable: string | null;
            /** Profit */
            profit: string | null;
            /** Tx */
            tx: string;
            /** Opened At */
            opened_at: number;
        };
        /** Protocol */
        Protocol: {
            /** Address */
            address?: string | null;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /**
             * Funded
             * @default 0
             */
            funded: string;
            /**
             * Reserved
             * @default 0
             */
            reserved: string;
            /**
             * Available
             * @default 0
             */
            available: string;
            /**
             * Status
             * @default awaiting_deployment
             */
            status: string;
            /**
             * Token Configured
             * @default false
             */
            token_configured: boolean;
            /** Contracts */
            contracts?: components["schemas"]["Series"][];
            /** Activity */
            activity?: components["schemas"]["TradeEvent"][];
            /** Checked At */
            checked_at?: string | null;
            /**
             * Index Synced
             * @default false
             */
            index_synced: boolean;
            /** Indexed Block */
            indexed_block?: number | null;
        };
        /** ProviderQuote */
        ProviderQuote: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Price */
            price: number;
            /** Region */
            region?: string | null;
            /** Instance */
            instance?: string | null;
            /** Scope */
            scope: string;
            /** Source Url */
            source_url: string;
            /** Updated At */
            updated_at: string;
            /**
             * Included
             * @default false
             */
            included: boolean;
        };
        /** PublicConfig */
        PublicConfig: {
            /** Privy App Id */
            privy_app_id: string;
            /** Chain Id */
            chain_id: number;
            /** Explorer Url */
            explorer_url: string;
            /** Token Address */
            token_address: string | null;
            /** Market Address */
            market_address: string | null;
            /** Usdg Address */
            usdg_address: string;
            /** Fee Bps */
            fee_bps: number;
            /**
             * Fee Free Above
             * @default 5000
             */
            fee_free_above: string;
            /** Trading Enabled */
            trading_enabled: boolean;
        };
        /** Quote */
        Quote: {
            /**
             * Indicative
             * @default true
             */
            indicative: boolean;
            /** Premium */
            premium: string;
            /** Fee */
            fee: string;
            /** Cost */
            cost: string;
            /** Max Loss */
            max_loss: string;
            /** Max Payout */
            max_payout: string;
            /** Payout */
            payout: string;
            /** Profit */
            profit: string;
            /** Breakeven */
            breakeven: string | null;
            /** Breakeven Pct */
            breakeven_pct: string;
            /** Reference Price */
            reference_price: string | null;
            /** Collateral Required */
            collateral_required: string;
            /** Fee Bps */
            fee_bps: number;
            /** Reason */
            reason: string;
            /** Units Raw */
            units_raw?: string | null;
            /** Cost Raw */
            cost_raw?: string | null;
            /** Contract Address */
            contract_address?: string | null;
            /** Deadline */
            deadline?: number | null;
            /** Expiry */
            expiry?: number | null;
        };
        /** QuoteRequest */
        QuoteRequest: {
            /**
             * Market
             * @default h100-sxm
             * @enum {string}
             */
            market: "h100-sxm" | "a100-80" | "b200";
            /**
             * Side
             * @default call
             * @enum {string}
             */
            side: "call" | "put";
            /**
             * Premium
             * @default 2
             */
            premium: number | string;
            /**
             * Move Pct
             * @default 4
             */
            move_pct: number | string;
            /** Address */
            address?: string | null;
        };
        /** Series */
        Series: {
            /** Address */
            address: string;
            /** Asset */
            asset: string;
            /** Open At */
            open_at: number;
            /** Expiry */
            expiry: number;
            /** Base Price */
            base_price: number;
            /** Current Index */
            current_index: number;
            /** Call Premium */
            call_premium: string;
            /** Put Premium */
            put_premium: string;
            /** Quote Valid Until */
            quote_valid_until: number;
            /** Observation Time */
            observation_time: number;
            /** Funded */
            funded: string;
            /** Reserved */
            reserved: string;
            /** Available */
            available: string;
            /** Total Shares */
            total_shares: string;
            /** Final Index */
            final_index: number;
            /** Settled */
            settled: boolean;
            /** Cancelled */
            cancelled: boolean;
            /** Paused */
            paused: boolean;
            /** Position Count */
            position_count: number;
            /** Phase */
            phase: string;
        };
        /** Snapshot */
        Snapshot: {
            /** Markets */
            markets: components["schemas"]["Market"][];
            network: components["schemas"]["Network"];
            /** Server Time */
            server_time: string;
            /** Collection Interval */
            collection_interval: number;
            /**
             * Data Source
             * @default GPU Economy
             */
            data_source: string;
            /**
             * Source Url
             * @default https://gpueconomy.com/data
             */
            source_url: string;
            /**
             * License
             * @default CC BY 4.0
             */
            license: string;
            /**
             * Trading Enabled
             * @default false
             */
            trading_enabled: boolean;
        };
        /** TradeEvent */
        TradeEvent: {
            /** Tx */
            tx: string;
            /** Log Index */
            log_index: number;
            /** Block */
            block: number;
            /** Timestamp */
            timestamp: number;
            /** Kind */
            kind: string;
            /** Wallet */
            wallet?: string | null;
            /** Position Id */
            position_id?: number | null;
            /** Amount */
            amount?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    public_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
        };
    };
    snapshot_api_v1_markets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    history_api_v1_history__market__get: {
        parameters: {
            query?: {
                range?: "1h" | "6h" | "24h";
            };
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    methodology_api_v1_methodology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    receipts_api_v1_receipts_get: {
        parameters: {
            query?: {
                market?: "h100-sxm" | "a100-80" | "b200";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receipt_api_v1_receipts__digest__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    access_api_v1_access__address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Access"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_api_v1_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    protocol_api_v1_protocol_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Protocol"];
                };
            };
        };
    };
    portfolio_api_v1_portfolio__address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leaderboard_api_v1_leaderboard_get: {
        parameters: {
            query?: {
                period?: "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_v1_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
